### ISSUE TITLE
[FEAT] 사용자당 등록 가능한 루틴 최대 개수 지정

### ISSUE THREAD

**Issue by pje1740** [pje1740/routinder_server#18]
## SUMMARY

사용자당 등록 가능한 루틴의 최대 개수가 필요합니다. (기간이 종료되지 않은 루틴. active 루틴이라고 표현하겠습니다.)
그리고 현재 기획에서는 하루에 최대 6개의 루틴이라고 나와있습니다만, 등록 때마다 계산을 도는 것이 비효율적이라고 판단이 됩니다. 

### AS-IS
- 달력 칸마다 최대 스티커 6개 출력 (월, 주 무관)
- active 루틴 개수 제한 없음
- 하루에 최대 6개의 루틴까지만 등록 가능

### TO-BE
- 월간 달력은 6개, 주간 달력은 8개 (혹은 칸이 허용하는 범위 내에서 최대)
- active 루틴 개수 제한
- 일별 기준으로 제한하지 않고 등록된 순서 오름차순으로 스티커 노출 (등록한 순서대로 최대 6개, 8개 스티커 노출)

@yurabahng 
- active 루틴을 최대 몇개까지로 제한하면 적당할까요? 10개 정도로 생각 중인데, 더 적절한 수치가 있다면 의견 주세요!
- 특정 날짜의 루틴이 6개, 8개가 넘어가면 이에 대한 indicator가 달력에 표시되면 좋겠다는 생각은 드는데, 혹 이견이 있거나 다른 방식으로 해결할 수 있다면 의견 주세요! 🙂

**Comment by yurabahng** [comment]
@pje1740 @jiyoon1156  메일 알림들을 이제 봤네요.. :( 
애플 알림 시간 지정 요약에 지메일을 같이 설정해버린 제 불찰입니다.. ㅜㅜ 알림 설정 다시 원복하겠습니다..


1. active 루틴을 최대 몇개까지로 제한하면 적당할까요? 10개 정도로 생각 중인데, 더 적절한 수치가 있다면 의견 주세요!
> 넵 10개 좋습니다 :) 기간이 종료되지 않은 루틴을 10개 제한하는 것으로 기획서 수정해둘게요~

2. 특정 날짜의 루틴이 6개, 8개가 넘어가면 이에 대한 indicator가 달력에 표시되면 좋겠다는 생각은 드는데, 혹 이견이 있거나 다른 방식으로 해결할 수 있다면 의견 주세요! 🙂
> 아 네넵, indicator가 달력에 표시되면 좋을 것 같은데, 지금 현재 디자인 간격으로는 indicator를 넣을 공간이 없어 보이네요.. 안그래도 8월 끝나기 전까지 웹, 로그인 정책 잡아서 기획서 공유드릴 예정인데, 이 것부터 우선 화면 설계 잡아보고, 이슈로 등록해서 한번 검토 요청드릴게요!
